### ISSUE TITLE
Hooking Pattern is outdated

### ISSUE THREAD

**Issue by CSY0N** [Svxy/TnyavnTos-GTA5-Mod-Menu#1]
this Hooking Pattern is outdated

would be cool if you can share Updated one.

hooking::increment_stat_event = static_cast<IncrementStatEvent>(Memory::pattern("48 89 5C 24 ? 48 89 74 24 ? 55 57 41 55 41 56 41 57 48 8B EC 48 83 EC 60 8B 79 30").count(1).get(0).get<void>(0));

**Comment by Svxy** [comment]
I've completely abandoned this project, I don't even have my old dev env setup anymore, sorry.
